name: Deploy

on:
  push:
    branches:
      - main
      - deploy
      - deploy/**

    paths:
      - package.json
      - package-lock.json
      - Dockerfile
      - .github/**
      - public/**
      - src/**
      - deploy/**

concurrency:
  group: arthouse-admin
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Setup cache
      - name: ⚡️ Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 🔑 Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dmitryhoncharuk/arthouse-admin:stage
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: 🚚 Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  k8s-config:
    name: k8s config
    runs-on: ubuntu-latest
    environment: Staging
    needs:
      - build
    steps:
      - name: Digitalocean login
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save Digitalocean k8s config
        run: doctl kubernetes cluster kubeconfig save ficdev

      - name: Create namespace
        run: kubectl create namespace arthouse || true

  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    needs:
      - k8s-config
    steps:
      - uses: actions/checkout@v3

      - name: Digitalocean login
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save Digitalocean k8s config
        run: doctl kubernetes cluster kubeconfig save ficdev

      - name: Apply k8s configs
        run: kubectl -n=arthouse apply -f deploy

      - name: Restart deployment
        run: kubectl -n=arthouse rollout restart deployment arthouse-admin-deployment
